{ data: '\n',
  type: 'text',
  next: 
   { type: 'tag',
     name: 'colgroup',
     attribs: {},
     children: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     next: 
      { data: '\n',
        type: 'text',
        next: [Object],
        prev: [Circular],
        parent: [Object] },
     prev: [Circular],
     parent: 
      { type: 'tag',
        name: 'table',
        attribs: [Object],
        children: [Object],
        next: [Object],
        prev: [Object],
        parent: [Object] } },
  prev: null,
  parent: 
   { type: 'tag',
     name: 'table',
     attribs: { class: 'sortable  stats_table', id: 'misc' },
     children: 
      [ [Circular],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     next: 
      { data: '\n',
        type: 'text',
        next: null,
        prev: [Circular],
        parent: [Object] },
     prev: 
      { data: '\n',
        type: 'text',
        next: [Circular],
        prev: null,
        parent: [Object] },
     parent: 
      { type: 'tag',
        name: 'div',
        attribs: [Object],
        children: [Object],
        next: [Object],
        prev: [Object],
        parent: [Object] } } }